package models

import (
	"crypto/ecdh"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"net"
	"strconv"
	"strings"
	"time"

	"gorm.io/gorm"
)

// WGServerConfig represents the Linux kernel WireGuard server configuration.
type WGServerConfig struct {
	ID            uint      `json:"id" gorm:"primaryKey"`
	InterfaceName string    `json:"interface_name" form:"interface_name" gorm:"default:wg0"`
	PrivateKey    string    `json:"private_key" form:"private_key"`
	PublicKey     string    `json:"public_key" form:"public_key"`
	ListenPort    int       `json:"listen_port" form:"listen_port" gorm:"default:51820"`
	Address       string    `json:"address" form:"address" gorm:"default:10.0.0.1/24"`
	MTU           int       `json:"mtu" form:"mtu" gorm:"default:1420"`
	PostUp        string    `json:"post_up" form:"post_up"`
	PostDown      string    `json:"post_down" form:"post_down"`
	Enabled       bool      `json:"enabled" form:"enabled" gorm:"default:true"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// WGPeer represents a connected client/peer in WireGuard.
type WGPeer struct {
	ID                  uint      `json:"id" form:"id" gorm:"primaryKey"`
	Name                string    `json:"name" form:"name" gorm:"not null"`
	PublicKey           string    `json:"public_key" form:"public_key" gorm:"not null"`
	PrivateKey          string    `json:"private_key,omitempty" form:"private_key"` // Optional: stored if generated by panel for 1-click client export
	PresharedKey        string    `json:"preshared_key,omitempty" form:"preshared_key"`
	AllowedIPs          string    `json:"allowed_ips" form:"allowed_ips" gorm:"not null"` // e.g. "10.0.0.2/32"
	Endpoint            string    `json:"endpoint,omitempty" form:"endpoint"`
	PersistentKeepalive int       `json:"persistent_keepalive" form:"persistent_keepalive" gorm:"default:25"`
	Enabled             bool      `json:"enabled" form:"enabled" gorm:"default:true"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

// DefaultPostUp returns the default iptables rules for NAT forwarding and TCP MSS clamping.
func DefaultPostUp(iface string) string {
	if iface == "" {
		iface = "%i"
	}
	return fmt.Sprintf("iptables -A FORWARD -i %s -j ACCEPT; iptables -A FORWARD -o %s -m state --state RELATED,ESTABLISHED -j ACCEPT; iptables -t nat -A POSTROUTING -o $(ip route show default | awk '{print $5; exit}') -j MASQUERADE; iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu", iface, iface)
}

// DefaultPostDown returns the default teardown iptables rules.
func DefaultPostDown(iface string) string {
	if iface == "" {
		iface = "%i"
	}
	return fmt.Sprintf("iptables -D FORWARD -i %s -j ACCEPT; iptables -D FORWARD -o %s -m state --state RELATED,ESTABLISHED -j ACCEPT; iptables -t nat -D POSTROUTING -o $(ip route show default | awk '{print $5; exit}') -j MASQUERADE; iptables -t mangle -D FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu", iface, iface)
}

// DeriveWGPublicKey derives the WireGuard (Curve25519) public key from base64 private key.
func DeriveWGPublicKey(privKeyB64 string) (string, error) {
	privBytes, err := base64.StdEncoding.DecodeString(strings.TrimSpace(privKeyB64))
	if err != nil {
		return "", fmt.Errorf("invalid base64 private key: %w", err)
	}
	privKey, err := ecdh.X25519().NewPrivateKey(privBytes)
	if err != nil {
		return "", fmt.Errorf("invalid Curve25519 private key: %w", err)
	}
	return base64.StdEncoding.EncodeToString(privKey.PublicKey().Bytes()), nil
}

// GenerateWGKeyPair generates a Curve25519 keypair and returns (privateKey, publicKey, error).
func GenerateWGKeyPair() (string, string, error) {
	privKey, err := ecdh.X25519().GenerateKey(rand.Reader)
	if err != nil {
		return "", "", fmt.Errorf("failed to generate private key: %w", err)
	}
	privB64 := base64.StdEncoding.EncodeToString(privKey.Bytes())
	pubB64 := base64.StdEncoding.EncodeToString(privKey.PublicKey().Bytes())
	return privB64, pubB64, nil
}

// GetWGServerConfig loads or initializes the singleton server configuration.
func GetWGServerConfig(db *gorm.DB) (*WGServerConfig, error) {
	var cfg WGServerConfig
	err := db.First(&cfg).Error
	if err == nil {
		return &cfg, nil
	}
	if err != gorm.ErrRecordNotFound {
		return nil, err
	}

	// Generate default keys
	privKey, pubKey, err := GenerateWGKeyPair()
	if err != nil {
		return nil, err
	}

	cfg = WGServerConfig{
		InterfaceName: "wg0",
		PrivateKey:    privKey,
		PublicKey:     pubKey,
		ListenPort:    51820,
		Address:       "10.0.0.1/24",
		MTU:           1420,
		PostUp:        DefaultPostUp("%i"),
		PostDown:      DefaultPostDown("%i"),
		Enabled:       true,
		UpdatedAt:     time.Now(),
	}

	if err := db.Create(&cfg).Error; err != nil {
		return nil, err
	}
	return &cfg, nil
}

// GetNextAvailableIP scans existing peers and returns the next unused IP (/32) in the subnet.
func GetNextAvailableIP(db *gorm.DB, serverAddress string) string {
	// Parse server address, e.g. "10.0.0.1/24"
	ipStr := serverAddress
	if idx := strings.Index(ipStr, "/"); idx != -1 {
		ipStr = ipStr[:idx]
	}
	serverIP := net.ParseIP(ipStr).To4()
	if serverIP == nil {
		return "10.0.0.2/32"
	}

	// Get all existing peer IPs
	var peers []WGPeer
	db.Select("allowed_ips").Find(&peers)

	usedLastOctets := make(map[byte]bool)
	usedLastOctets[serverIP[3]] = true // server's own IP

	for _, p := range peers {
		for _, rawIP := range strings.Split(p.AllowedIPs, ",") {
			rawIP = strings.TrimSpace(rawIP)
			if idx := strings.Index(rawIP, "/"); idx != -1 {
				rawIP = rawIP[:idx]
			}
			pip := net.ParseIP(rawIP).To4()
			if pip != nil && pip[0] == serverIP[0] && pip[1] == serverIP[1] && pip[2] == serverIP[2] {
				usedLastOctets[pip[3]] = true
			}
		}
	}

	// Find the first available last octet starting from 2 up to 254
	for octet := 2; octet <= 254; octet++ {
		if !usedLastOctets[byte(octet)] {
			return fmt.Sprintf("%d.%d.%d.%d/32", serverIP[0], serverIP[1], serverIP[2], octet)
		}
	}

	// Fallback
	return fmt.Sprintf("%d.%d.%d.2/32", serverIP[0], serverIP[1], serverIP[2])
}

// ParsePort parses port string safely with fallback.
func ParsePort(portStr string, defaultPort int) int {
	p, err := strconv.Atoi(strings.TrimSpace(portStr))
	if err != nil || p <= 0 || p > 65535 {
		return defaultPort
	}
	return p
}
