package wireguard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"

	"gorm.io/gorm"

	applogger "xray-panel/internal/logger"
	"xray-panel/internal/models"
)

// PeerRuntimeStats holds real-time WireGuard metrics for a peer.
type PeerRuntimeStats struct {
	PublicKey       string    `json:"public_key"`
	Endpoint        string    `json:"endpoint"`
	AllowedIPs      string    `json:"allowed_ips"`
	LatestHandshake time.Time `json:"latest_handshake"`
	HandshakeAgo    string    `json:"handshake_ago"`
	TransferRx      int64     `json:"transfer_rx"`
	TransferTx      int64     `json:"transfer_tx"`
	TransferRxHuman string    `json:"transfer_rx_human"`
	TransferTxHuman string    `json:"transfer_tx_human"`
	IsOnline        bool      `json:"is_online"`
}

// ServiceStatus holds overall systemd and interface status.
type ServiceStatus struct {
	IsLinux         bool   `json:"is_linux"`
	IsInstalled     bool   `json:"is_installed"`
	IsActive        bool   `json:"is_active"`
	IsEnabled       bool   `json:"is_enabled"`
	InterfaceName   string `json:"interface_name"`
	ListenPort      int    `json:"listen_port"`
	PublicKey       string `json:"public_key"`
	Address         string `json:"address"`
	TotalPeers      int    `json:"total_peers"`
	ActivePeers     int    `json:"active_peers"`
	OnlinePeers     int    `json:"online_peers"`
	PortConflict    bool   `json:"port_conflict"`
	ConflictInbound string `json:"conflict_inbound"`
	IPv4Forwarding  bool   `json:"ipv4_forwarding"`
	IPv6Forwarding  bool   `json:"ipv6_forwarding"`
}

// Manager handles kernel-level WireGuard configuration and systemd services.
type Manager struct {
	db       *gorm.DB
	confPath string
}

// NewManager creates a WireGuard manager.
func NewManager(db *gorm.DB) *Manager {
	confPath := "/etc/wireguard/wg0.conf"
	if runtime.GOOS != "linux" {
		confPath = filepath.Join(os.TempDir(), "wg0.conf")
	}
	return &Manager{
		db:       db,
		confPath: confPath,
	}
}

// IsInstalled returns true if WireGuard tools ('wg' and 'wg-quick') are found.
func IsInstalled() bool {
	if runtime.GOOS != "linux" {
		return false
	}
	_, err1 := exec.LookPath("wg")
	_, err2 := exec.LookPath("wg-quick")
	return err1 == nil && err2 == nil
}

// CheckPortConflict checks if the specified port is already used by an enabled Xray inbound.
func CheckPortConflict(db *gorm.DB, port int) (bool, string) {
	var inbounds []models.Inbound
	if err := db.Where("port = ? AND enabled = ?", port, true).Find(&inbounds).Error; err == nil && len(inbounds) > 0 {
		return true, inbounds[0].Tag
	}
	return false, ""
}

// CheckForwarding checks if IPv4 and IPv6 packet forwarding is enabled in the Linux kernel.
func CheckForwarding() (ipv4 bool, ipv6 bool) {
	if runtime.GOOS != "linux" {
		return false, false
	}
	if data, err := os.ReadFile("/proc/sys/net/ipv4/ip_forward"); err == nil {
		ipv4 = strings.TrimSpace(string(data)) == "1"
	}
	if data, err := os.ReadFile("/proc/sys/net/ipv6/conf/all/forwarding"); err == nil {
		ipv6 = strings.TrimSpace(string(data)) == "1"
	}
	return ipv4, ipv6
}

// EnableForwarding writes persistent sysctl config and applies IPv4 & IPv6 packet forwarding.
func EnableForwarding() error {
	if runtime.GOOS != "linux" {
		return nil
	}

	confContent := `# Generated by Xray Panel - WireGuard forwarding configuration
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.ipv6.conf.default.forwarding = 1
`
	_ = os.MkdirAll("/etc/sysctl.d", 0755)
	_ = os.WriteFile("/etc/sysctl.d/99-wireguard.conf", []byte(confContent), 0644)

	// Apply immediately to runtime
	_ = exec.Command("sysctl", "-w", "net.ipv4.ip_forward=1").Run()
	_ = exec.Command("sysctl", "-w", "net.ipv6.conf.all.forwarding=1").Run()
	_ = exec.Command("sysctl", "-w", "net.ipv6.conf.default.forwarding=1").Run()
	_ = exec.Command("sysctl", "--system").Run()

	applogger.Info("IPv4 & IPv6 packet forwarding enabled and persisted to /etc/sysctl.d/99-wireguard.conf")
	return nil
}

// SetupEnvironment installs wireguard-tools, loads kernel module, and enables IPv4/IPv6 forwarding.
func SetupEnvironment() (string, error) {
	if runtime.GOOS != "linux" {
		return "", fmt.Errorf("一键环境准备仅支持 Linux 系统")
	}

	var sb strings.Builder

	// 1. Enable IPv4 & IPv6 forwarding
	if err := EnableForwarding(); err != nil {
		sb.WriteString(fmt.Sprintf("⚠️ 开启内核转发失败: %v\n", err))
	} else {
		sb.WriteString("✓ 已开启并持久化 IPv4 & IPv6 数据包转发\n")
	}

	// 2. Load wireguard kernel module
	_ = exec.Command("modprobe", "wireguard").Run()

	// 3. Install wireguard-tools if missing
	if !IsInstalled() {
		osRelease, _ := os.ReadFile("/etc/os-release")
		osStr := strings.ToLower(string(osRelease))

		var cmd *exec.Cmd
		if strings.Contains(osStr, "ubuntu") || strings.Contains(osStr, "debian") {
			cmd = exec.Command("bash", "-c", "DEBIAN_FRONTEND=noninteractive apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y wireguard-tools")
		} else if strings.Contains(osStr, "centos") || strings.Contains(osStr, "rhel") || strings.Contains(osStr, "rocky") || strings.Contains(osStr, "almalinux") || strings.Contains(osStr, "fedora") {
			cmd = exec.Command("bash", "-c", "which dnf >/dev/null 2>&1 && dnf install -y epel-release wireguard-tools || yum install -y epel-release wireguard-tools")
		} else if strings.Contains(osStr, "alpine") {
			cmd = exec.Command("apk", "add", "wireguard-tools")
		} else if strings.Contains(osStr, "arch") {
			cmd = exec.Command("pacman", "-Sy", "--noconfirm", "wireguard-tools")
		} else {
			cmd = exec.Command("apt-get", "install", "-y", "wireguard-tools")
		}

		out, err := cmd.CombinedOutput()
		if err != nil {
			sb.WriteString(fmt.Sprintf("❌ 安装 wireguard-tools 失败: %s: %v\n", strings.TrimSpace(string(out)), err))
			return sb.String(), fmt.Errorf("安装 wireguard-tools 失败: %s", string(out))
		}
		sb.WriteString("✓ 已成功安装 wireguard-tools 依赖\n")
	} else {
		sb.WriteString("✓ wireguard-tools 已就绪\n")
	}

	return sb.String(), nil
}

// GetStatus returns the current service status and peer counts.
func (m *Manager) GetStatus() (*ServiceStatus, error) {
	serverCfg, err := models.GetWGServerConfig(m.db)
	if err != nil {
		return nil, err
	}

	conflict, conflictTag := CheckPortConflict(m.db, serverCfg.ListenPort)
	ipv4Fwd, ipv6Fwd := CheckForwarding()

	status := &ServiceStatus{
		IsLinux:         runtime.GOOS == "linux",
		IsInstalled:     IsInstalled(),
		InterfaceName:   serverCfg.InterfaceName,
		ListenPort:      serverCfg.ListenPort,
		PublicKey:       serverCfg.PublicKey,
		Address:         serverCfg.Address,
		PortConflict:    conflict,
		ConflictInbound: conflictTag,
		IPv4Forwarding:  ipv4Fwd,
		IPv6Forwarding:  ipv6Fwd,
	}

	var totalPeers int64
	var activePeers int64
	m.db.Model(&models.WGPeer{}).Count(&totalPeers)
	m.db.Model(&models.WGPeer{}).Where("enabled = ?", true).Count(&activePeers)
	status.TotalPeers = int(totalPeers)
	status.ActivePeers = int(activePeers)

	if runtime.GOOS == "linux" && status.IsInstalled {
		unit := fmt.Sprintf("wg-quick@%s", serverCfg.InterfaceName)
		outActive, _ := exec.Command("systemctl", "is-active", unit).Output()
		status.IsActive = strings.TrimSpace(string(outActive)) == "active"

		outEnabled, _ := exec.Command("systemctl", "is-enabled", unit).Output()
		status.IsEnabled = strings.TrimSpace(string(outEnabled)) == "enabled"

		if status.IsActive {
			stats, _ := m.GetPeerRuntimeStats()
			for _, st := range stats {
				if st.IsOnline {
					status.OnlinePeers++
				}
			}
		}
	}

	return status, nil
}

// ServiceAction controls systemd service actions: start, stop, restart, enable, disable.
func (m *Manager) ServiceAction(action string) error {
	if runtime.GOOS != "linux" {
		return fmt.Errorf("systemd service control is only supported on Linux")
	}
	serverCfg, err := models.GetWGServerConfig(m.db)
	if err != nil {
		return err
	}
	unit := fmt.Sprintf("wg-quick@%s", serverCfg.InterfaceName)

	switch action {
	case "start":
		// Ensure IPv4 and IPv6 forwarding is enabled
		_ = EnableForwarding()

		// Ensure config is written before starting
		if err := m.WriteConfigFile(); err != nil {
			return fmt.Errorf("failed to write config: %w", err)
		}
		out, err := exec.Command("systemctl", "start", unit).CombinedOutput()
		if err != nil {
			return fmt.Errorf("start failed: %s: %w", string(out), err)
		}
	case "stop":
		out, err := exec.Command("systemctl", "stop", unit).CombinedOutput()
		if err != nil {
			return fmt.Errorf("stop failed: %s: %w", string(out), err)
		}
	case "restart":
		// Ensure IPv4 and IPv6 forwarding is enabled
		_ = EnableForwarding()

		if err := m.WriteConfigFile(); err != nil {
			return fmt.Errorf("failed to write config: %w", err)
		}
		out, err := exec.Command("systemctl", "restart", unit).CombinedOutput()
		if err != nil {
			return fmt.Errorf("restart failed: %s: %w", string(out), err)
		}
	case "enable":
		out, err := exec.Command("systemctl", "enable", unit).CombinedOutput()
		if err != nil {
			return fmt.Errorf("enable failed: %s: %w", string(out), err)
		}
	case "disable":
		out, err := exec.Command("systemctl", "disable", unit).CombinedOutput()
		if err != nil {
			return fmt.Errorf("disable failed: %s: %w", string(out), err)
		}
	default:
		return fmt.Errorf("unsupported action: %s", action)
	}
	return nil
}

// GenerateWG0Conf creates the /etc/wireguard/wg0.conf content.
func (m *Manager) GenerateWG0Conf(server *models.WGServerConfig, peers []models.WGPeer) string {
	var sb strings.Builder

	sb.WriteString("# Generated by Xray Panel - Kernel WireGuard Server\n")
	sb.WriteString("[Interface]\n")
	sb.WriteString(fmt.Sprintf("Address = %s\n", server.Address))
	sb.WriteString(fmt.Sprintf("ListenPort = %d\n", server.ListenPort))
	sb.WriteString(fmt.Sprintf("PrivateKey = %s\n", server.PrivateKey))
	if server.MTU > 0 {
		sb.WriteString(fmt.Sprintf("MTU = %d\n", server.MTU))
	}
	if strings.TrimSpace(server.PostUp) != "" {
		sb.WriteString(fmt.Sprintf("PostUp = %s\n", strings.TrimSpace(server.PostUp)))
	}
	if strings.TrimSpace(server.PostDown) != "" {
		sb.WriteString(fmt.Sprintf("PostDown = %s\n", strings.TrimSpace(server.PostDown)))
	}

	for _, p := range peers {
		if !p.Enabled {
			continue
		}
		sb.WriteString("\n")
		sb.WriteString(fmt.Sprintf("# Peer: %s (ID: %d)\n", p.Name, p.ID))
		sb.WriteString("[Peer]\n")
		sb.WriteString(fmt.Sprintf("PublicKey = %s\n", p.PublicKey))
		if strings.TrimSpace(p.PresharedKey) != "" {
			sb.WriteString(fmt.Sprintf("PresharedKey = %s\n", strings.TrimSpace(p.PresharedKey)))
		}
		sb.WriteString(fmt.Sprintf("AllowedIPs = %s\n", p.AllowedIPs))
		if strings.TrimSpace(p.Endpoint) != "" {
			sb.WriteString(fmt.Sprintf("Endpoint = %s\n", strings.TrimSpace(p.Endpoint)))
		}
		if p.PersistentKeepalive > 0 {
			sb.WriteString(fmt.Sprintf("PersistentKeepalive = %d\n", p.PersistentKeepalive))
		}
	}

	return sb.String()
}

// WriteConfigFile writes the configuration to /etc/wireguard/wg0.conf with 0600 permissions.
func (m *Manager) WriteConfigFile() error {
	serverCfg, err := models.GetWGServerConfig(m.db)
	if err != nil {
		return err
	}

	var peers []models.WGPeer
	if err := m.db.Find(&peers).Error; err != nil {
		return err
	}

	confContent := m.GenerateWG0Conf(serverCfg, peers)

	dir := filepath.Dir(m.confPath)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("failed to create wireguard dir %s: %w", dir, err)
	}

	if err := os.WriteFile(m.confPath, []byte(confContent), 0600); err != nil {
		return fmt.Errorf("failed to write %s: %w", m.confPath, err)
	}

	applogger.Info("WireGuard configuration written to %s", m.confPath)
	return nil
}

// SyncConfig writes the config and hot-reloads it via wg syncconf for zero downtime.
// If the interface is not active, it only writes the config.
func (m *Manager) SyncConfig(portChanged bool) error {
	if err := m.WriteConfigFile(); err != nil {
		return err
	}

	if runtime.GOOS != "linux" || !IsInstalled() {
		return nil
	}

	serverCfg, err := models.GetWGServerConfig(m.db)
	if err != nil {
		return err
	}
	unit := fmt.Sprintf("wg-quick@%s", serverCfg.InterfaceName)

	outActive, _ := exec.Command("systemctl", "is-active", unit).Output()
	isActive := strings.TrimSpace(string(outActive)) == "active"

	if !isActive {
		return nil
	}

	// If port changed, wg syncconf cannot change listen port on a running device; restart unit
	if portChanged {
		applogger.Info("WireGuard listen port changed, restarting %s", unit)
		out, err := exec.Command("systemctl", "restart", unit).CombinedOutput()
		if err != nil {
			return fmt.Errorf("restart on port change failed: %s: %w", string(out), err)
		}
		return nil
	}

	// Hot reload peers seamlessly via wg-quick strip piped into wg syncconf
	stripCmd := exec.Command("wg-quick", "strip", m.confPath)
	strippedOut, err := stripCmd.Output()
	if err != nil {
		// Fallback to restart
		applogger.Warn("wg-quick strip failed, falling back to restart: %v", err)
		exec.Command("systemctl", "restart", unit).Run()
		return nil
	}

	syncCmd := exec.Command("wg", "syncconf", serverCfg.InterfaceName, "/dev/stdin")
	syncCmd.Stdin = bytes.NewReader(strippedOut)
	if syncOut, err := syncCmd.CombinedOutput(); err != nil {
		applogger.Warn("wg syncconf failed: %s, restarting: %v", string(syncOut), err)
		exec.Command("systemctl", "restart", unit).Run()
		return nil
	}

	applogger.Info("WireGuard peers hot-synced successfully on %s", serverCfg.InterfaceName)
	return nil
}

// GetPeerRuntimeStats queries `wg show wg0 dump` and returns stats per peer public key.
func (m *Manager) GetPeerRuntimeStats() (map[string]PeerRuntimeStats, error) {
	result := make(map[string]PeerRuntimeStats)
	if runtime.GOOS != "linux" || !IsInstalled() {
		return result, nil
	}

	serverCfg, err := models.GetWGServerConfig(m.db)
	if err != nil {
		return result, err
	}

	out, err := exec.Command("wg", "show", serverCfg.InterfaceName, "dump").Output()
	if err != nil {
		return result, err
	}

	now := time.Now()
	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	for i, line := range lines {
		if i == 0 {
			// First line is interface info
			continue
		}
		fields := strings.Split(line, "\t")
		if len(fields) < 8 {
			continue
		}

		pubKey := fields[0]
		endpoint := fields[2]
		allowedIPs := fields[3]
		handshakeEpoch, _ := strconv.ParseInt(fields[4], 10, 64)
		rxBytes, _ := strconv.ParseInt(fields[5], 10, 64)
		txBytes, _ := strconv.ParseInt(fields[6], 10, 64)

		var handshakeTime time.Time
		handshakeAgo := "未连接"
		isOnline := false

		if handshakeEpoch > 0 {
			handshakeTime = time.Unix(handshakeEpoch, 0)
			diff := now.Sub(handshakeTime)
			if diff < 3*time.Minute {
				isOnline = true
			}
			handshakeAgo = formatDurationAgo(diff)
		}

		result[pubKey] = PeerRuntimeStats{
			PublicKey:       pubKey,
			Endpoint:        endpoint,
			AllowedIPs:      allowedIPs,
			LatestHandshake: handshakeTime,
			HandshakeAgo:    handshakeAgo,
			TransferRx:      rxBytes,
			TransferTx:      txBytes,
			TransferRxHuman: formatBytesHuman(rxBytes),
			TransferTxHuman: formatBytesHuman(txBytes),
			IsOnline:        isOnline,
		}
	}

	return result, nil
}

// GenerateClientWGConfig generates standard wg0.conf for the client VPS / device.
func (m *Manager) GenerateClientWGConfig(server *models.WGServerConfig, peer *models.WGPeer, serverHost string) string {
	var sb strings.Builder

	privKey := peer.PrivateKey
	if strings.TrimSpace(privKey) == "" {
		privKey = "<客户端私钥 (由公钥推导或客户端自行生成)>"
	}

	sb.WriteString("[Interface]\n")
	sb.WriteString(fmt.Sprintf("PrivateKey = %s\n", privKey))
	sb.WriteString(fmt.Sprintf("Address = %s\n", peer.AllowedIPs))
	sb.WriteString("DNS = 1.1.1.1, 8.8.8.8\n")
	if server.MTU > 0 {
		sb.WriteString(fmt.Sprintf("MTU = %d\n", server.MTU))
	}

	sb.WriteString("\n[Peer]\n")
	sb.WriteString(fmt.Sprintf("PublicKey = %s\n", server.PublicKey))
	if strings.TrimSpace(peer.PresharedKey) != "" {
		sb.WriteString(fmt.Sprintf("PresharedKey = %s\n", peer.PresharedKey))
	}
	sb.WriteString(fmt.Sprintf("Endpoint = %s:%d\n", serverHost, server.ListenPort))
	sb.WriteString("AllowedIPs = 0.0.0.0/0, ::/0\n")
	keepalive := peer.PersistentKeepalive
	if keepalive <= 0 {
		keepalive = 25
	}
	sb.WriteString(fmt.Sprintf("PersistentKeepalive = %d\n", keepalive))

	return sb.String()
}

// GenerateClientXrayJSON generates the Xray Outbound JSON configuration for the client VPS.
func (m *Manager) GenerateClientXrayJSON(server *models.WGServerConfig, peer *models.WGPeer, serverHost string) (string, error) {
	privKey := peer.PrivateKey
	if strings.TrimSpace(privKey) == "" {
		privKey = "<客户端私钥>"
	}

	ipAddr := peer.AllowedIPs
	if !strings.Contains(ipAddr, "/") {
		ipAddr = ipAddr + "/32"
	}

	mtu := server.MTU
	if mtu <= 0 {
		mtu = 1420
	}

	outbound := map[string]interface{}{
		"tag":      fmt.Sprintf("wg-%s", strings.ToLower(strings.ReplaceAll(peer.Name, " ", "-"))),
		"protocol": "wireguard",
		"settings": map[string]interface{}{
			"secretKey": privKey,
			"address":   []string{ipAddr},
			"peers": []map[string]interface{}{
				{
					"publicKey": server.PublicKey,
					"endpoint":  fmt.Sprintf("%s:%d", serverHost, server.ListenPort),
				},
			},
			"mtu": mtu,
		},
	}

	b, err := json.MarshalIndent(outbound, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// Helpers

func formatBytesHuman(b int64) string {
	const unit = 1024
	if b < unit {
		return fmt.Sprintf("%d B", b)
	}
	div, exp := int64(unit), 0
	for n := b / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(b)/float64(div), "KMGTPE"[exp])
}

func formatDurationAgo(d time.Duration) string {
	if d < 5*time.Second {
		return "刚刚"
	}
	if d < time.Minute {
		return fmt.Sprintf("%d 秒前", int(d.Seconds()))
	}
	if d < time.Hour {
		return fmt.Sprintf("%d 分钟前", int(d.Minutes()))
	}
	if d < 24*time.Hour {
		return fmt.Sprintf("%d 小时前", int(d.Hours()))
	}
	return fmt.Sprintf("%d 天前", int(d.Hours()/24))
}

// CleanHost returns clean hostname/IP stripped of port.
func CleanHost(hostWithPort string) string {
	if strings.Contains(hostWithPort, ":") {
		h, _, err := net.SplitHostPort(hostWithPort)
		if err == nil {
			return h
		}
	}
	return hostWithPort
}
